# Generated by Django 4.2 on 2023-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateField()),
                ('calories', models.IntegerField(verbose_name='kcal')),
                ('fats', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Fats')),
                ('saturated_fat', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='SatF')),
                ('mono_unsaturated_fat', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='MonF')),
                ('poly_unsaturated_fat', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='PlyF')),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Carb')),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='Sugr')),
                ('starch', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Strc')),
                ('fibre', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Fibr')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Prot')),
                ('salt', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Salt')),
            ],
        ),
    ]
