# Generated by Django 4.2 on 2023-04-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlabel',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='fibre',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='mono_unsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='poly_unsaturated_fat',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='saturated_fat',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='starch',
        ),
        migrations.RemoveField(
            model_name='foodlabel',
            name='sugars',
        ),
    ]
