# Generated by Django 4.2 on 2023-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_remove_foodlabel_fats_remove_foodlabel_fibre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlabel',
            name='calories',
            field=models.IntegerField(verbose_name='Kcal'),
        ),
    ]
