# Generated by Django 3.2.8 on 2021-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='when it happened')),
                ('time0', models.TimeField(verbose_name='exactly when')),
                ('problem', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dose',
            name='slot',
            field=models.CharField(blank=True, choices=[('', 'No slot'), ('A1', 'A1 ~ 09:00'), ('A2', 'A2 ~ 12:00'), ('A3', 'A3 ~ 14:00'), ('B1', 'B1 ~ 16:00'), ('B2', 'B2 ~ 18:30'), ('B3', 'B3 ~ 21:30')], max_length=2),
        ),
    ]
