# Generated by Django 3.2.8 on 2021-11-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20211104_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='date')),
                ('time0', models.TimeField(verbose_name='time')),
                ('description', models.TextField(verbose_name='What happened')),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
