# Generated by Django 3.2.8 on 2021-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_auto_20211104_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='date measured')),
                ('time0', models.TimeField(verbose_name='time measured')),
                ('higher', models.IntegerField(verbose_name='systolic/higher')),
                ('lower', models.IntegerField(verbose_name='diastolic/lower')),
                ('heart_rate', models.IntegerField(null=True, verbose_name='beats per minute (or zero)')),
            ],
        ),
    ]
