# Generated by Django 3.2.8 on 2021-11-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_bloodpressure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='date')),
                ('description', models.TextField(verbose_name='Exercise notes')),
            ],
        ),
        migrations.CreateModel(
            name='Oedema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='date')),
                ('notes', models.TextField(verbose_name='Status of oedema today')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='date measured')),
                ('pounds', models.FloatField(verbose_name='pounds')),
                ('kilos', models.FloatField(verbose_name='kilos')),
            ],
        ),
    ]
