# Generated by Django 3.2.8 on 2021-11-21 15:29

import daily.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_auto_20211121_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatigue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='date')),
                ('time0', models.TimeField(verbose_name='time')),
                ('level', models.IntegerField(validators=[daily.models.out_of_ten], verbose_name='Tiredness (out of 10)')),
            ],
        ),
    ]
