# Generated by Django 4.1.7 on 2023-04-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=100, verbose_name='reason to take')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='when this schedule came into force')),
                ('reason', models.CharField(max_length=150, verbose_name='why it was changed')),
            ],
        ),
        migrations.CreateModel(
            name='TirednessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(unique=True, verbose_name='tiredness level')),
                ('description', models.CharField(max_length=30, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_micrograms', models.IntegerField()),
                ('num_tablets', models.FloatField(default=1.0)),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nx.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('date0', models.DateField(primary_key=True, serialize=False, verbose_name='date observed')),
                ('pounds', models.FloatField(default=0, verbose_name='pounds')),
                ('kilos', models.FloatField(default=0, verbose_name='kilos')),
                ('am_higher', models.IntegerField(blank=True, null=True, verbose_name='Morning systolic')),
                ('am_lower', models.IntegerField(blank=True, null=True, verbose_name='Morning diastolic')),
                ('am_rate', models.IntegerField(blank=True, null=True, verbose_name='Morning resting heart rate')),
                ('pm_higher', models.IntegerField(blank=True, null=True, verbose_name='Afternoon systolic')),
                ('pm_lower', models.IntegerField(blank=True, null=True, verbose_name='Afternoon diastolic')),
                ('pm_rate', models.IntegerField(blank=True, null=True, verbose_name='Afternoon resting heart rate')),
                ('other_rate', models.IntegerField(blank=True, null=True, verbose_name='Extra resting heart rate')),
                ('oedema', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oedema (swelling)')),
                ('dizzy_spells', models.IntegerField(default=0, null=True, verbose_name='Dizzy spells')),
                ('exercise', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exercise notes')),
                ('events', models.TextField(blank=True, max_length=500, null=True, verbose_name='Events/Notes')),
                ('tiredness', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='nx.tirednesslevel', to_field='rating')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, choices=[('', 'No slot'), ('A1', 'A1 ~ 09:00'), ('A2', 'A2 ~ 12:00'), ('A3', 'A3 ~ 14:00'), ('B1', 'B1 ~ 16:00'), ('B2', 'B2 ~ 19:00'), ('B3', 'B3 ~ 21:30')], max_length=2)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nx.schedule')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nx.tablet')),
            ],
        ),
    ]
