# Generated by Django 3.2.8 on 2021-11-23 08:45

from django.db import migrations, models
import django.db.models.deletion
import nx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=100, verbose_name='reason to take')),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('date0', models.DateField(primary_key=True, serialize=False, verbose_name='date measured')),
                ('pounds', models.FloatField(verbose_name='pounds')),
                ('kilos', models.FloatField(verbose_name='kilos')),
                ('am_higher', models.IntegerField(verbose_name='Morning systolic')),
                ('am_lower', models.IntegerField(verbose_name='Morning diastolic')),
                ('pm_higher', models.IntegerField(verbose_name='Afternoon systolic')),
                ('pm_lower', models.IntegerField(verbose_name='Afternoon diastolic')),
                ('exercise', models.CharField(blank=True, max_length=100, verbose_name='Exercise notes')),
                ('fatigue_score', models.IntegerField(validators=[nx.models.out_of_ten], verbose_name='Tiredness (out of 10)')),
                ('oedema', models.CharField(blank=True, max_length=50, verbose_name='Oedema (swelling)')),
                ('events', models.TextField(blank=True, max_length=500, verbose_name='Events/Notes')),
                ('notes', models.TextField(verbose_name='Status of oedema today')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.DateField(verbose_name='when this schedule came into force')),
                ('reason', models.CharField(max_length=150, verbose_name='why it was changed')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_micrograms', models.IntegerField()),
                ('num_tablets', models.FloatField(default=1.0)),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nx.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, choices=[('', 'No slot'), ('A1', 'A1 ~ 09:00'), ('A2', 'A2 ~ 12:00'), ('A3', 'A3 ~ 14:00'), ('B1', 'B1 ~ 16:00'), ('B2', 'B2 ~ 19:00'), ('B3', 'B3 ~ 21:30')], max_length=2)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nx.schedule')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nx.tablet')),
            ],
        ),
    ]
