# Generated by Django 3.2.8 on 2021-11-23 15:23

from django.db import migrations, models
import nx.models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obs',
            name='notes',
        ),
        migrations.AlterField(
            model_name='obs',
            name='am_higher',
            field=models.IntegerField(blank=True, null=True, verbose_name='Morning systolic'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='am_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='Morning diastolic'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='events',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Events/Notes'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='exercise',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exercise notes'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='fatigue_score',
            field=models.IntegerField(null=True, validators=[nx.models.out_of_ten], verbose_name='Tiredness (out of 10)'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='kilos',
            field=models.FloatField(default=0, verbose_name='kilos'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='oedema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Oedema (swelling)'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='pm_higher',
            field=models.IntegerField(blank=True, null=True, verbose_name='Afternoon systolic'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='pm_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='Afternoon diastolic'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='pounds',
            field=models.FloatField(default=0, verbose_name='pounds'),
        ),
    ]
