# Generated by Django 4.2 on 2023-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='second_micrograms',
            field=models.IntegerField(null=True),
        ),
    ]
