# Generated by Django 4.2 on 2023-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0002_tablet_second_micrograms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='slot',
            field=models.CharField(blank=True, choices=[('', 'No slot'), ('A1', 'A1 ~ 10:00'), ('A2', 'A2 ~ 12:00'), ('A3', 'A3 ~ 14:00'), ('B1', 'B1 ~ 16:00'), ('B2', 'B2 ~ 19:00'), ('B3', 'B3 ~ 21:30')], max_length=2),
        ),
    ]
