# Generated by Django 4.2 on 2023-05-08 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0003_alter_dose_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='num_days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='stagger doses over'),
        ),
    ]
