# Generated by Django 3.2.8 on 2021-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0004_auto_20211209_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obs',
            name='date0',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='date observed'),
        ),
    ]
