# Generated by Django 3.2.8 on 2022-01-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nx', '0005_alter_obs_date0'),
    ]

    operations = [
        migrations.AddField(
            model_name='obs',
            name='dizzy_spells',
            field=models.IntegerField(default=0, null=True, verbose_name='Dizzy spells'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='tiredness',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='nx.tirednesslevel', to_field='rating'),
        ),
        migrations.AlterField(
            model_name='tirednesslevel',
            name='rating',
            field=models.IntegerField(unique=True, verbose_name='tiredness level'),
        ),
    ]
